apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  destination:
    namespace: sonarqube
    server: https://kubernetes.default.svc
  project: default
  source:
    path: devops/sonarqube/manifests
    repoURL: https://jihulab.com/devopsvip/myiac.git
    targetRevision: main
    directory:
      recurse: false
  syncPolicy:
    automated: 
      prune: true
    syncOptions:
      - CreateNamespace=true