apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-agent
  namespace: argocd
spec:
  destination:
    namespace: jenkins
    server: https://kubernetes.default.svc
  project: default
  source:
    path: devops/jenkins/agent-manifests
    repoURL: https://jihulab.com/devopsvip/myiac.git
    targetRevision: main
    directory:
      recurse: false
  syncPolicy:
    automated: 
      prune: true
    syncOptions:
      - CreateNamespace=true