apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-server-ingress
  namespace: gitlab
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: gitlab.idevops.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitlab
            port:
              name: web