apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: directory-guestbook
  namespace: argocd
spec:
  destination:
    namespace: directory-guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    path: guestbook
    repoURL: https://jihulab.com/devops_course/argocd-example-apps.git
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true